//<C and C++ compiler>
//<Matthew Krumholz>
//<11/24/2025> 

//<discription of code> Lets a user change durration of sweep in microseconds how manytimes the sweep happens and the the start and end of the sweep. The sweep is a sine wave that is linear.
//<Why?> This will be used to control the peizo electric powersupply to release nanoparticles.
//<5> It works!
//<Board functions used?>  sweep_api, rp.h, uses the 125Mhz fr channels.

#include <stdio.h>
#include <unistd.h>
#include "rp.h"
#include "rp_sweep.h"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
using namespace rp_sweep_api;                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
int main() {
    // Init the base generator API
    if (rp_Init() != RP_OK) {
        fprintf(stderr, "rp_Init failed\n");
        return -1;
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    if (rp_SWInit() != RP_OK) {
        fprintf(stderr, "rp_SWInit failed\n");
        return -1;
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    float start_freq = 100000;  // 100 kHz
    float stop_freq  = 300000;  // 300 kHz
    int   sweep_time = 100000;  // 100,000 us = 100 ms
    int   sweep_amount = 1.0; // number of times the sweep happens
    float offset = .5;
   
    rp_SWResetAll();                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    // Set sweep parameters
    rp_GenOffset(RP_CH_1, .5);
    rp_SWSetStartFreq(RP_CH_1, start_freq);                                                                                                                                                                                                                                                                                                                                                                                                                                                
    rp_SWSetStopFreq (RP_CH_1, stop_freq);                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    rp_SWSetTime     (RP_CH_1, sweep_time);                                                                                                                                                                                                                                                                                                                                                                                                                                                
    rp_SWSetMode     (RP_CH_1, RP_GEN_SWEEP_MODE_LINEAR);                                                                                                                                                                                                                                                                                                                                                                                                                                  
    rp_SWSetDir      (RP_CH_1, RP_GEN_SWEEP_DIR_NORMAL);  // just sweep upward
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    // configure wave output.
    rp_GenReset();                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    rp_GenWaveform(RP_CH_1, RP_WAVEFORM_SINE);                                                                                                                                                                                                                                                                                                                                                                                                                                             
    rp_GenAmp(RP_CH_1, .5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    // Enable sweep for this channel
    rp_SWGenSweep(RP_CH_1, true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
   
    rp_GenOutEnable(RP_CH_1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    rp_SWRun();                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    // Wait for length of wave, if more it will repeat the wave gen, so if we want to do multiple sweeps change sweep amount.
    usleep(sweep_time * sweep_amount);                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    rp_SWStop();                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    rp_GenOutDisable(RP_CH_1);                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    rp_SWRelease();                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    rp_Release();                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    return 0;
}
