# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/matta/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-18384-DESKTOP-QON3TB4/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.cache/wt} [current_project]
set_property parent.project_path {C:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.srcs/sources_1/new/adc_ratio.v}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/matta/Documents/2025 Fall/Research/RP_Dev_Par_Lev/verilog-vhdl/test/ADC_ratio/ADC_ratio.srcs/constrs_1/new/const.xdc}}]


synth_design -top adc_ratio -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adc_ratio.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file adc_ratio_utilization_synth.rpt -pb adc_ratio_utilization_synth.pb"
